import type { Product } from "./db-products";

// Static products data - 13 products with images
export const staticProducts: Omit<Product, "id" | "createdAt" | "updatedAt">[] = [
  {
    name: "Premium Industrial Equipment",
    nameAr: null,
    nameFa: null,
    description: "High-quality industrial equipment designed for heavy-duty operations. Built with durable materials and advanced engineering for maximum efficiency and longevity. Perfect for manufacturing facilities and industrial applications.",
    descriptionAr: null,
    descriptionFa: null,
    price: 12500.00,
    compareAtPrice: 15000.00,
    sku: "PROD-001",
    stock: 15,
    category: "Industrial Equipment",
    images: ["/images/product1.jpeg"],
    featured: true,
    active: true,
  },
  {
    name: "Professional Warehouse Storage System",
    nameAr: null,
    nameFa: null,
    description: "Complete warehouse storage solution with modular shelving units. Optimize your storage space with this versatile system that adapts to your needs. Easy to assemble and expandable.",
    descriptionAr: null,
    descriptionFa: null,
    price: 8500.00,
    compareAtPrice: 10000.00,
    sku: "PROD-002",
    stock: 8,
    category: "Warehouse Solutions",
    images: ["/images/product2.jpeg"],
    featured: false,
    active: true,
  },
  {
    name: "Advanced Logistics Management Software",
    nameAr: null,
    nameFa: null,
    description: "Comprehensive logistics management platform with real-time tracking, inventory management, and automated reporting. Streamline your operations with cutting-edge technology.",
    descriptionAr: null,
    descriptionFa: null,
    price: 25000.00,
    compareAtPrice: null,
    sku: "PROD-003",
    stock: 5,
    category: "Software Solutions",
    images: ["/images/product3.jpeg"],
    featured: true,
    active: true,
  },
  {
    name: "Heavy-Duty Cargo Containers",
    nameAr: null,
    nameFa: null,
    description: "Standard shipping containers built to withstand harsh conditions. Weather-resistant and secure, perfect for international shipping and storage. Available in multiple sizes.",
    descriptionAr: null,
    descriptionFa: null,
    price: 3200.00,
    compareAtPrice: 3800.00,
    sku: "PROD-004",
    stock: 25,
    category: "Shipping Containers",
    images: ["/images/product4.jpeg"],
    featured: false,
    active: true,
  },
  {
    name: "Automated Conveyor Belt System",
    nameAr: null,
    nameFa: null,
    description: "State-of-the-art conveyor system for efficient material handling. Reduces manual labor and increases productivity. Customizable length and configuration to fit your facility.",
    descriptionAr: null,
    descriptionFa: null,
    price: 18500.00,
    compareAtPrice: 22000.00,
    sku: "PROD-005",
    stock: 3,
    category: "Material Handling",
    images: ["/images/product5.jpeg"],
    featured: true,
    active: true,
  },
  {
    name: "Forklift Truck - Electric",
    nameAr: null,
    nameFa: null,
    description: "Environmentally friendly electric forklift with powerful lifting capacity. Low maintenance and quiet operation. Ideal for indoor warehouses and distribution centers.",
    descriptionAr: null,
    descriptionFa: null,
    price: 45000.00,
    compareAtPrice: 52000.00,
    sku: "PROD-006",
    stock: 6,
    category: "Material Handling",
    images: ["/images/product6.jpeg"],
    featured: false,
    active: true,
  },
  {
    name: "Temperature-Controlled Storage Unit",
    nameAr: null,
    nameFa: null,
    description: "Premium cold storage solution for perishable goods. Advanced temperature control system ensures optimal conditions. Perfect for food and pharmaceutical storage.",
    descriptionAr: null,
    descriptionFa: null,
    price: 28000.00,
    compareAtPrice: 33000.00,
    sku: "PROD-007",
    stock: 4,
    category: "Specialized Storage",
    images: ["/images/product7.jpeg"],
    featured: true,
    active: true,
  },
  {
    name: "Pallet Racking System",
    nameAr: null,
    nameFa: null,
    description: "Robust pallet racking system for high-density storage. Maximize vertical space utilization with this reliable and safe storage solution. Easy installation and adjustment.",
    descriptionAr: null,
    descriptionFa: null,
    price: 6500.00,
    compareAtPrice: 7500.00,
    sku: "PROD-008",
    stock: 12,
    category: "Warehouse Solutions",
    images: ["/images/product8.jpeg"],
    featured: false,
    active: true,
  },
  {
    name: "RFID Inventory Tracking System",
    nameAr: null,
    nameFa: null,
    description: "Advanced RFID technology for real-time inventory tracking. Improve accuracy and reduce manual counting. Includes scanners, tags, and management software.",
    descriptionAr: null,
    descriptionFa: null,
    price: 15000.00,
    compareAtPrice: 18000.00,
    sku: "PROD-009",
    stock: 7,
    category: "Technology Solutions",
    images: ["/images/product9.jpeg"],
    featured: false,
    active: true,
  },
  {
    name: "Loading Dock Equipment Package",
    nameAr: null,
    nameFa: null,
    description: "Complete loading dock solution with dock levelers, seals, and safety equipment. Enhance efficiency and safety at your loading bays. Professional installation included.",
    descriptionAr: null,
    descriptionFa: null,
    price: 22000.00,
    compareAtPrice: 26000.00,
    sku: "PROD-010",
    stock: 5,
    category: "Loading Equipment",
    images: ["/images/product10.jpeg"],
    featured: true,
    active: true,
  },
  {
    name: "Automated Sorting Machine",
    nameAr: null,
    nameFa: null,
    description: "High-speed automated sorting system for packages and parcels. Increases sorting capacity and reduces errors. Ideal for distribution centers and fulfillment operations.",
    descriptionAr: null,
    descriptionFa: null,
    price: 95000.00,
    compareAtPrice: 110000.00,
    sku: "PROD-011",
    stock: 2,
    category: "Automation Equipment",
    images: ["/images/product11.jpeg"],
    featured: true,
    active: true,
  },
  {
    name: "Portable Weighing Scale System",
    nameAr: null,
    nameFa: null,
    description: "Precision weighing system for accurate measurement of goods. Portable and easy to use. Features digital display and multiple weighing modes. Battery operated.",
    descriptionAr: null,
    descriptionFa: null,
    price: 1200.00,
    compareAtPrice: 1500.00,
    sku: "PROD-012",
    stock: 20,
    category: "Measurement Equipment",
    images: ["/images/product12.jpeg"],
    featured: false,
    active: true,
  },
  {
    name: "Security & Access Control System",
    nameAr: null,
    nameFa: null,
    description: "Comprehensive security solution for warehouses and facilities. Includes access control, surveillance cameras, and alarm systems. Protect your assets with advanced security technology.",
    descriptionAr: null,
    descriptionFa: null,
    price: 18000.00,
    compareAtPrice: 22000.00,
    sku: "PROD-013",
    stock: 9,
    category: "Security Systems",
    images: ["/images/product13.jpeg"],
    featured: false,
    active: true,
  },
];

// Generate IDs for static products
export function getStaticProducts(): Product[] {
  return staticProducts.map((product, index) => ({
    ...product,
    id: `static-${index + 1}`,
    createdAt: new Date(),
    updatedAt: new Date(),
  }));
}

// Get static product by ID
export function getStaticProductById(id: string): Product | null {
  const products = getStaticProducts();
  return products.find(p => p.id === id) || null;
}

